### ISSUE TITLE
Unable to import the project into STM32CubeIDE

### ISSUE THREAD

**Issue by satur9nine** [benedekkupper/stm32-i2c-hid#3]
I tried importing this project into STM32CubeIDE 1.12.1 but none of the following methods worked:

- "Existing projects into workspace": Could only find a project located at Drivers/CMSIS/Core/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/.project which is clearly not this project
- "Import an Existing STM32CubeMX Configuration File (.ioc)": Import ended up without any i2c code, end up with a main.c file without the i2c hid code

I believe the problem is that the `.project` file is in the `.gitignore` but is necessary for a proper import into eclipse and/or STM32CubeIDE .

**Comment by benedekkupper** [comment]
Thank you for your report, I've added the missing file, I hope it works with this change.

**Comment by satur9nine** [comment]
Thanks I was able to import the project and after following the instructions to generate the usage tables with python I had to make a couple minor adjustments before I could compile and link successfully:

1. Add the follow project paths to the includes: `hid-rdf/include` and `hid-rdf/hid-rp`
2. From Preferences > Toolchain Manager install the GNU Tools for STM32 (11.3rel1) and set the project to build with that, because STM32CubeIDE comes with version 10.3 of GCC which does not support C++20

I now successfully obtained stm32-i2c-hid.elf though I have not yet run it.

**Comment by benedekkupper** [comment]
I have updated the path in the readme so the `hid-rdf/include` is completely phased out from use. I am successfully using the `GNU Tools for STM32 (10.3-2021.10)` toolchain to build the project, so I'm baffled that it doesn't work for you.
